keys:
  - &admin_tassilo 91EBE87016391323642A6803B966009D57E69CC6
  - &admin_melody 778755C4893709525F6E62BCC2A819CA37DE8B61
  - &admin_fiasko BCD42664340540E058422472AF9E0821C4A08B44
  - &admin_adb 6F9E5DCB111D958035A7B0084653A66E940BBA1A
  - &admin_marcel 46D4682470DBE26790DF9433446F3B093DF81C6A

  # test key
  - &test age1925katzy5gws3f9hnvnlwspu6trxf488arwt6ayw3urg2mgumqhszxnmqh
  - &mno001 age1h5zuv4pxjv94gpmjgfahkzmd6c5hfcdmk48vegzagze24a8x6p3q2muxh0
  - &ns-mno001 age19nann8gw4mnmnjzq0ztg0vsjsf8kafehhygqpccww5yqjnmdqgmqyp3nm4
  - &portal-mno001 age18s3336el6n7txkpcqpugp0yy9a3d4rv8qcrjnrf505anehs0pycqx3u6m6
creation_rules:
  - path_regex: secrets/management/secrets.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *mno001
  - path_regex: secrets/management/portal.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *portal-mno001
  - path_regex: secrets/management/rfc2136/bind.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *ns-mno001
