keys:
  - &admin_tassilo 91EBE87016391323642A6803B966009D57E69CC6
  - &admin_melody 778755C4893709525F6E62BCC2A819CA37DE8B61
  - &admin_fiasko BCD42664340540E058422472AF9E0821C4A08B44
  - &admin_adb 6F9E5DCB111D958035A7B0084653A66E940BBA1A
  - &admin_marcel 46D4682470DBE26790DF9433446F3B093DF81C6A
  - &admin_maurice 5CEA328E2A000F3834ECED462DC4542D86651C1E

  - &svc-hv01 age1h5zuv4pxjv94gpmjgfahkzmd6c5hfcdmk48vegzagze24a8x6p3q2muxh0
  - &svc-ns01 age19nann8gw4mnmnjzq0ztg0vsjsf8kafehhygqpccww5yqjnmdqgmqyp3nm4
  - &svc-portal01 age18s3336el6n7txkpcqpugp0yy9a3d4rv8qcrjnrf505anehs0pycqx3u6m6
  - &svc-auth01 age12vlqwh94qv2dnz89zuc4q0dw5clpjxyxa2tetvyuvq7rt7mpg3nq5gmjtq
  - &svc-pg01 age1xncen8ley579x7upvswpey5w84yyn2qf44y0t3pf9qh66vmvueeqj8zgk3
  - &svc-cloud01 age1swpyhunuhrmz0z6vpvhhk6asseggcmu696qr05hhmq02njjcna6s4dp4am
  - &svc-dcim01 age19eew0cu2pwzvdcl08ghftwy928fpvk50txxn8fswrhh52m2k4d7qpl72ka
  - &svc-lists01 age1szvwsfrfhkmx4a3e8zt7286w2u3m2ctvj9nj07guvczcumhauqks2apeme
  - &svc-vault01 age12n7ckcmw9j9qym430lv00l6ax3xklljjt3502s9vxkn43qqpqfyqqusqrg
  - &svc-lg01 age1mpakhhssx0ha5nv72hcyzecz0uy2lqnwduqkdyhdkexqe7gruvqqj0gqx0
  - &svc-adm01 age1yg56aehyj58nytm6c8d2d67mrds8s9rzjstyds0grval5kjm7dcq7pfpv8
  - &svc-prom01 age1s5rwy7xa9ytmkrd0ch9eqe0dfe6u2ew5su2353jtgpjnhl5lq34s85lqjt
  - &svc-obs01 age1pkdglrt6a2ne03sc68hpj4vesmdtjelul9srl768ra2lf7jj8vnqxjreq4
  - &svc-mari01 age1yatz0dnu3644dyzz03w84suzyyf0a25elmprvfudpqpv9s8nr4wsqctdq8
  - &svc-web01 age17z4tnuns8hqjjl9mqqeve3d2vmshw4xxldkcp4h6le6rhal3laqs897jnc
  - &svc-prom02 age1w3t9hz6hqjdhy8y49h42zeqnalew88hsnpekw66y38ckp6mkusgq5shh39
  - &svc-orga01 age1f9zr5zpev2gev8pd5fgldp83hrdu2uecqfefqv06unh8lh7hudms8ju9e0
  - &svc-mta01 age1dch6m69xayedr76psrdurae3j3jyrw9fgeq4wklt0gnanl6sxqpq2wnf8l
  - &svc-tix01 age1dch6m69xayedr76psrdurae3j3jyrw9fgeq4wklt0gnanl6sxqpq2wnf8l
creation_rules:
  - path_regex: secrets/management/(restic/svc-hv01|secrets).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-hv01
  - path_regex: secrets/management/portal.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-portal01
  - path_regex: secrets/management/rfc2136/bind.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-ns01
  - path_regex: secrets/management/rfc2136/wiki.dd-ix.net.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-hv01
  - path_regex: secrets/management/rfc2136/portal.dd-ix.net.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-portal01
  - path_regex: secrets/management/(rfc2136/auth.dd-ix.net|auth).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-auth01
  - path_regex: secrets/management/(rfc2136/tickets.dd-ix.net|tickets).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-tix01
  - path_regex: secrets/management/(rfc2136/svc-pg01.dd-ix.net|postgres/postgres).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-pg01 
  - path_regex: secrets/management/(rfc2136/(cloud|office).dd-ix.net|cloud).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-cloud01
  - path_regex: secrets/management/(rfc2136/dcim.dd-ix.net|dcim).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-dcim01
  - path_regex: secrets/management/(rfc2136/lists.dd-ix.net|lists).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-lists01
  - path_regex: secrets/management/(rfc2136/vault.dd-ix.net|vault).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-vault01
  - path_regex: secrets/management/(rfc2136/lg.dd-ix.net|lg).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-lg01
  - path_regex: secrets/management/adm.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-adm01
  - path_regex: secrets/management/rfc2136/svc-prom01.dd-ix.net.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-prom01
  - path_regex: secrets/management/rfc2136/svc-prom02.dd-ix.net.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-prom02
  - path_regex: secrets/management/(rfc2136/obs.dd-ix.net|obs).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-obs01
  - path_regex: secrets/management/(rfc2136/svc-mari01.dd-ix.net|mari).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-mari01
  - path_regex: secrets/management/(rfc2136/((www|content|talks).)?dd-ix.net|web).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-web01
  - path_regex: secrets/management/(rfc2136/orga.dd-ix.net|orga).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-orga01
  - path_regex: secrets/management/(rfc2136/svc-mta01.dd-ix.net|mta).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        - *admin_maurice
        age:
        - *svc-mta01
