keys:
  - &admin_tassilo 91EBE87016391323642A6803B966009D57E69CC6
  - &admin_melody 778755C4893709525F6E62BCC2A819CA37DE8B61
  - &admin_fiasko BCD42664340540E058422472AF9E0821C4A08B44
  - &admin_adb 6F9E5DCB111D958035A7B0084653A66E940BBA1A
  - &admin_marcel 46D4682470DBE26790DF9433446F3B093DF81C6A

  - &svc-hv01 age1h5zuv4pxjv94gpmjgfahkzmd6c5hfcdmk48vegzagze24a8x6p3q2muxh0
  - &svc-ns01 age19nann8gw4mnmnjzq0ztg0vsjsf8kafehhygqpccww5yqjnmdqgmqyp3nm4
  - &svc-portal01 age18s3336el6n7txkpcqpugp0yy9a3d4rv8qcrjnrf505anehs0pycqx3u6m6
  - &svc-auth01 age12vlqwh94qv2dnz89zuc4q0dw5clpjxyxa2tetvyuvq7rt7mpg3nq5gmjtq
  - &svc-pg01 age1xncen8ley579x7upvswpey5w84yyn2qf44y0t3pf9qh66vmvueeqj8zgk3
  - &svc-cloud01 age1swpyhunuhrmz0z6vpvhhk6asseggcmu696qr05hhmq02njjcna6s4dp4am
  - &svc-dcim01 age19eew0cu2pwzvdcl08ghftwy928fpvk50txxn8fswrhh52m2k4d7qpl72ka
  - &svc-lists01 age1kq5036xjkesuaa6aa48mdnp7unm90a26exll5vd7lceuqn39pulqrsezkw
  - &svc-vault01 age12n7ckcmw9j9qym430lv00l6ax3xklljjt3502s9vxkn43qqpqfyqqusqrg
  - &svc-lg01 age1mpakhhssx0ha5nv72hcyzecz0uy2lqnwduqkdyhdkexqe7gruvqqj0gqx0
creation_rules:
  - path_regex: secrets/management/(restic/svc-hv01|secrets).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-hv01
  - path_regex: secrets/management/portal.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-portal01
  - path_regex: secrets/management/rfc2136/bind.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-ns01
  - path_regex: secrets/management/rfc2136/((www|content|wiki|orga).)?dd-ix.net.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-hv01
  - path_regex: secrets/management/rfc2136/portal.dd-ix.net.yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-portal01
  - path_regex: secrets/management/(rfc2136/auth.dd-ix.net|auth).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-auth01
  - path_regex: secrets/management/(rfc2136/svc-pg01.dd-ix.net|postgres/postgres).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-pg01 
  - path_regex: secrets/management/(rfc2136/cloud.dd-ix.net|rfc2136/office.dd-ix.net|cloud).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-cloud01
  - path_regex: secrets/management/(rfc2136/dcim.dd-ix.net|dcim).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-dcim01
  - path_regex: secrets/management/(rfc2136/lists.dd-ix.net|lists).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-lists01
  - path_regex: secrets/management/(rfc2136/vault.dd-ix.net|vault).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-vault01
  - path_regex: secrets/management/(rfc2136/lg.dd-ix.net|lg).yaml
    key_groups:
      - pgp:
        - *admin_tassilo
        - *admin_melody
        - *admin_fiasko
        - *admin_adb
        - *admin_marcel
        age:
        - *svc-lg01
